# Generated by Django 2.2.6 on 2019-10-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20191008_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentatio',
            new_name='comentario',
        ),
    ]
