# Generated by Django 2.2.6 on 2019-10-16 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_turistico', '0009_docidentificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='doc_identificador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ponto_turistico.DocIdentificador'),
        ),
    ]
