# Generated by Django 2.2.6 on 2019-10-16 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_turistico', '0010_pontoturistico_doc_identificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docidentificador',
            old_name='descriptioin',
            new_name='description',
        ),
    ]
